### ISSUE TITLE
Unclear asset licensing

### ISSUE THREAD

**Issue by kozross** [voithos/elemental-one#1]
'Some sort of Creative Commons license' is rather vague - there's a _world_ of difference between CC0 and CC-BY-ND-SA, for example. ATTRIBUTION.md doesn't specify what licenses each asset it under. Could you please clarify this?

**Comment by voithos** [comment]
I suppose I assumed that people could just look up the original asset if they were interested, but your point is fair. The attribution file has been updated to specify licenses.
